name: Dependencies Updater
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update-dependencies-axum:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
        name: Check out repo code
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        name: install cargo-edit and cargo-generate
        with:
          tool: cargo-edit,cargo-generate
      - name: temporarily change package name for cargo-upgrade to work
        run: sed -i "s/\{\{project-name\}\}/axum-template/" Cargo.toml
        working-directory: ./axum-template
      - name: run cargo-upgrade
        run: cargo upgrade
        working-directory: ./axum-template
      - name: restore package name
        run: sed -i "s/axum-template/\{\{project-name\}\}/" Cargo.toml
        working-directory: ./axum-template
      - name: cleanup dasel binary
        run: rm dasel
      - name: verify that build works correctly
        run: echo -e "[values]\nadditional_routes = \"\"" > values.toml && cargo generate -a --path axum-template -n axum-template-test --values-file values.toml && cd axum-template-test && cargo check
      - name: verify that health check works
        working-directory: ./axum-template-test
        run: |
          set -euo pipefail
          cargo run -q &
          timeout 20 bash -c 'until curl -sf http://127.0.0.1:8080/healthz; do sleep 1; done'
          curl http://127.0.0.1:8080/healthz -o test.txt
          [[ $(cat test.txt) == "ok" ]] || { echo "assertion failed!"; rm test.txt; exit 1; }
          rm test.txt
          killall axum-template-test
      - name: cleanup template test
        run: rm -rf axum-template-test
      - run: git status
      - run: git add axum-template
      - name: push new branch
        id: push-branch
        run: |
          set -euo pipefail
          if ! git diff --cached --quiet; then
            export BRANCH_NAME=axum-template-update-$(date +%d%m%y%H%M)
            echo "BRANCH_NAME="$BRANCH_NAME"" >> $GITHUB_ENV
            git checkout -B $BRANCH_NAME
            git config --global user.name "Github Actions Bot"
            git config --global user.email "actions@github.com"
            git commit -m "auto-update for axum template's dependencies"
            git push -u origin $BRANCH_NAME
            echo "new_branch=true" >> $GITHUB_OUTPUT
          fi
      - name: open PR
        uses: actions/github-script@v9
        if: steps.push-branch.outputs.new_branch == 'true'
        with:
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "update axum template dependencies",
              head: process.env.BRANCH_NAME,
              base: "master"
            })
